name = "Killswitch Docs"
description = "Документация по товарам и клавиатурам"
homepage = "https://docs.killswit.ch"
tags = ["technical", "docs", "dark", "customizable", "search", "documentation"]
features = ["technical", "docs", "dark", "customizable", "search", "documentation"]
min_version = "0.76.0"

[author]
  name = "Killswitch"
  homepage = "https://killswit.ch/"
